ActiveRecord::Base.connection.exec_query("Truncate table paises")
puts "-----------------------------------------------------------------------------"
puts "Se realizó un Truncate a la tabla de 'paises' tipo de base de datos 'MySQL'."
puts "-----------------------------------------------------------------------------"

puts "-----------------------------------------------------------------------------"
puts "Comenzando a insertar paises."
puts "-----------------------------------------------------------------------------"
Paise.create(:name => "	Afganistán	", :capital => "	Kabul	", :continente => "	Asia	")
Paise.create(:name => "	Albania	", :capital => "	Tirana	", :continente => "	Europa	")
Paise.create(:name => "	Alemania	", :capital => "	Berlín	", :continente => "	Europa	")
Paise.create(:name => "	Andorra	", :capital => "	Andorra la Vieja	", :continente => "	Europa	")
Paise.create(:name => "	Angola	", :capital => "	Luanda	", :continente => "	África	")
Paise.create(:name => "	Antigua y Barbuda	", :capital => "	Saint John's	", :continente => "	América	")
Paise.create(:name => "	Arabia Saudita	", :capital => "	Riad	", :continente => "	Asia	")
Paise.create(:name => "	Argelia	", :capital => "	Argel	", :continente => "	África	")
Paise.create(:name => "	Argentina	", :capital => "	Buenos Aires	", :continente => "	América	")
Paise.create(:name => "	Armenia	", :capital => "	Ereván	", :continente => "	Europa	")
Paise.create(:name => "	Australia	", :capital => "	Canberra	", :continente => "	Oceanía	")
Paise.create(:name => "	Austria	", :capital => "	Viena	", :continente => "	Europa	")
Paise.create(:name => "	Azerbaiyán	", :capital => "	Bakú	", :continente => "	Asia	")
Paise.create(:name => "	Bahamas	", :capital => "	Nasáu	", :continente => "	América	")
Paise.create(:name => "	Baréin	", :capital => "	Manama	", :continente => "	Asia	")
Paise.create(:name => "	Bangladesh	", :capital => "	Daca	", :continente => "	Asia	")
Paise.create(:name => "	Barbados	", :capital => "	Bridgetown	", :continente => "	América	")
Paise.create(:name => "	Bélgica	", :capital => "	Bruselas	", :continente => "	Europa	")
Paise.create(:name => "	Belice	", :capital => "	Belmopán	", :continente => "	América	")
Paise.create(:name => "	Benín	", :capital => "	Porto-Novo	", :continente => "	África	")
Paise.create(:name => "	Bielorrusia	", :capital => "	Minsk	", :continente => "	Europa	")
Paise.create(:name => "	Bolivia	", :capital => "	Sucre	", :continente => "	América	")
Paise.create(:name => "	Bosnia y Herzegovina	", :capital => "	Sarajevo	", :continente => "	Europa	")
Paise.create(:name => "	Botsuana	", :capital => "	Gaborone	", :continente => "	África	")
Paise.create(:name => "	Brasil	", :capital => "	Brasilia	", :continente => "	América	")
Paise.create(:name => "	Brunéi	", :capital => "	Bandar Seri Begawan	", :continente => "	Asia	")
Paise.create(:name => "	Bulgaria	", :capital => "	Sofía	", :continente => "	Europa	")
Paise.create(:name => "	Burkina Faso	", :capital => "	Uagadugú	", :continente => "	África	")
Paise.create(:name => "	Burundi	", :capital => "	Buyumbura	", :continente => "	África	")
Paise.create(:name => "	Bután	", :capital => "	Timbu	", :continente => "	Asia	")
Paise.create(:name => "	Cabo Verde	", :capital => "	Praia	", :continente => "	África	")
Paise.create(:name => "	Camboya	", :capital => "	Phnom Penh	", :continente => "	Asia	")
Paise.create(:name => "	Camerún	", :capital => "	Yaundé	", :continente => "	África	")
Paise.create(:name => "	Canadá	", :capital => "	Ottawa	", :continente => "	América	")
Paise.create(:name => "	República Centroafricana	", :capital => "	Bangui	", :continente => "	África	")
Paise.create(:name => "	Chad	", :capital => "	Yamena	", :continente => "	África	")
Paise.create(:name => "	República Checa	", :capital => "	Praga	", :continente => "	Europa	")
Paise.create(:name => "	Chile	", :capital => "	Santiago de Chile	", :continente => "	América	")
Paise.create(:name => "	China	", :capital => "	Pekín	", :continente => "	Asia	")
Paise.create(:name => "	Chipre	", :capital => "	Nicosia	", :continente => "	Asia	")
Paise.create(:name => "	Colombia	", :capital => "	Bogotá	", :continente => "	América	")
Paise.create(:name => "	Comoras	", :capital => "	Moroni	", :continente => "	África	")
Paise.create(:name => "	República del Congo	", :capital => "	Brazzaville	", :continente => "	África	")
Paise.create(:name => "	República Democrática del Congo	", :capital => "	Kinsasa	", :continente => "	África	")
Paise.create(:name => "	Corea del Norte	", :capital => "	Pionyang	", :continente => "	Asia	")
Paise.create(:name => "	Corea del Sur	", :capital => "	Seúl	", :continente => "	Asia	")
Paise.create(:name => "	Costa de Marfil	", :capital => "	Yamusukro	", :continente => "	África	")
Paise.create(:name => "	Costa Rica	", :capital => "	San José	", :continente => "	América	")
Paise.create(:name => "	Croacia	", :capital => "	Zagreb	", :continente => "	Europa	")
Paise.create(:name => "	Cuba	", :capital => "	La Habana	", :continente => "	América	")
Paise.create(:name => "	Dinamarca	", :capital => "	Copenhague	", :continente => "	Europa	")
Paise.create(:name => "	Dominica	", :capital => "	Roseau	", :continente => "	América	")
Paise.create(:name => "	República Dominicana	", :capital => "	Santo Domingo	", :continente => "	América	")
Paise.create(:name => "	Ecuador	", :capital => "	Quito	", :continente => "	América	")
Paise.create(:name => "	Egipto	", :capital => "	El Cairo	", :continente => "	África	")
Paise.create(:name => "	El Salvador	", :capital => "	San Salvador	", :continente => "	América	")
Paise.create(:name => "	Emiratos Árabes Unidos	", :capital => "	Abu Dabi	", :continente => "	Asia	")
Paise.create(:name => "	Eritrea	", :capital => "	Asmara	", :continente => "	África	")
Paise.create(:name => "	Eslovaquia	", :capital => "	Bratislava	", :continente => "	Europa	")
Paise.create(:name => "	Eslovenia	", :capital => "	Liubliana	", :continente => "	Europa	")
Paise.create(:name => "	España	", :capital => "	Madrid	", :continente => "	Europa	")
Paise.create(:name => "	Estados Unidos	", :capital => "	Washington D. C.	", :continente => "	América	")
Paise.create(:name => "	Estonia	", :capital => "	Tallin	", :continente => "	Europa	")
Paise.create(:name => "	Etiopía	", :capital => "	Adís Abeba	", :continente => "	África	")
Paise.create(:name => "	Filipinas	", :capital => "	Manila	", :continente => "	Asia	")
Paise.create(:name => "	Finlandia	", :capital => "	Helsinki	", :continente => "	Europa	")
Paise.create(:name => "	Fiyi	", :capital => "	Suva	", :continente => "	Oceanía	")
Paise.create(:name => "	Francia	", :capital => "	París	", :continente => "	Europa	")
Paise.create(:name => "	Gabón	", :capital => "	Libreville	", :continente => "	África	")
Paise.create(:name => "	Gambia	", :capital => "	Banjul	", :continente => "	África	")
Paise.create(:name => "	Georgia	", :capital => "	Tiflis	", :continente => "	Asia	")
Paise.create(:name => "	Ghana	", :capital => "	Acra	", :continente => "	África	")
Paise.create(:name => "	Granada	", :capital => "	Saint George's	", :continente => "	América	")
Paise.create(:name => "	Grecia	", :capital => "	Atenas	", :continente => "	Europa	")
Paise.create(:name => "	Guatemala	", :capital => "	Ciudad de Guatemala	", :continente => "	América	")
Paise.create(:name => "	Guinea	", :capital => "	Conakry	", :continente => "	África	")
Paise.create(:name => "	Guinea-Bissau	", :capital => "	Bissau	", :continente => "	África	")
Paise.create(:name => "	Guinea Ecuatorial	", :capital => "	Malabo	", :continente => "	África	")
Paise.create(:name => "	Guyana	", :capital => "	Georgetown	", :continente => "	América	")
Paise.create(:name => "	Haití	", :capital => "	Puerto Príncipe	", :continente => "	América	")
Paise.create(:name => "	Honduras	", :capital => "	Tegucigalpa	", :continente => "	América	")
Paise.create(:name => "	Hungría	", :capital => "	Budapest	", :continente => "	Europa	")
Paise.create(:name => "	India	", :capital => "	Nueva Delhi	", :continente => "	Asia	")
Paise.create(:name => "	Indonesia	", :capital => "	Yakarta	", :continente => "	Asia	")
Paise.create(:name => "	Irán	", :capital => "	Teherán	", :continente => "	Asia	")
Paise.create(:name => "	Iraq	", :capital => "	Bagdad	", :continente => "	Asia	")
Paise.create(:name => "	Irlanda	", :capital => "	Dublín	", :continente => "	Europa	")
Paise.create(:name => "	Islandia	", :capital => "	Reikiavik	", :continente => "	Europa	")
Paise.create(:name => "	Israel	", :capital => "	Jerusalén	", :continente => "	Asia	")
Paise.create(:name => "	Italia	", :capital => "	Roma	", :continente => "	Europa	")
Paise.create(:name => "	Jamaica	", :capital => "	Kingston	", :continente => "	América	")
Paise.create(:name => "	Japón	", :capital => "	Tokio	", :continente => "	Asia	")
Paise.create(:name => "	Jordania	", :capital => "	Amán	", :continente => "	Asia	")
Paise.create(:name => "	Kazajistán	", :capital => "	Astaná	", :continente => "	Asia	")
Paise.create(:name => "	Kenia	", :capital => "	Nairobi	", :continente => "	África	")
Paise.create(:name => "	Kirguistán	", :capital => "	Biskek	", :continente => "	Asia	")
Paise.create(:name => "	Kiribati	", :capital => "	Tarawa	", :continente => "	Oceanía	")
Paise.create(:name => "	Kuwait	", :capital => "	Ciudad de Kuwait	", :continente => "	Asia	")
Paise.create(:name => "	Laos	", :capital => "	Vientián	", :continente => "	Asia	")
Paise.create(:name => "	Lesoto	", :capital => "	Maseru	", :continente => "	África	")
Paise.create(:name => "	Letonia	", :capital => "	Riga	", :continente => "	Europa	")
Paise.create(:name => "	Líbano	", :capital => "	Beirut	", :continente => "	Asia	")
Paise.create(:name => "	Libia	", :capital => "	Trípoli	", :continente => "	África	")
Paise.create(:name => "	Liechtenstein	", :capital => "	Vaduz	", :continente => "	Europa	")
Paise.create(:name => "	Lituania	", :capital => "	Vilna	", :continente => "	Europa	")
Paise.create(:name => "	Luxemburgo	", :capital => "	Luxemburgo	", :continente => "	Europa	")
Paise.create(:name => "	República de Macedonia	", :capital => "	Skopie	", :continente => "	Europa	")
Paise.create(:name => "	Madagascar	", :capital => "	Antananarivo	", :continente => "	África	")
Paise.create(:name => "	Malaui	", :capital => "	Lilongüe	", :continente => "	África	")
Paise.create(:name => "	Malasia	", :capital => "	Kuala Lumpur	", :continente => "	Asia	")
Paise.create(:name => "	Maldivas	", :capital => "	Malé	", :continente => "	Asia	")
Paise.create(:name => "	Malí	", :capital => "	Bamako	", :continente => "	África	")
Paise.create(:name => "	Malta	", :capital => "	La Valeta	", :continente => "	Europa	")
Paise.create(:name => "	Marruecos	", :capital => "	Rabat	", :continente => "	África	")
Paise.create(:name => "	Islas Marshall	", :capital => "	Majuro	", :continente => "	Oceanía	")
Paise.create(:name => "	Mauricio	", :capital => "	Port Louis	", :continente => "	África	")
Paise.create(:name => "	Mauritania	", :capital => "	Nuakchot	", :continente => "	África	")
Paise.create(:name => "	México	", :capital => "	Ciudad de México	", :continente => "	América	")
Paise.create(:name => "	Micronesia	", :capital => "	Palikir	", :continente => "	Oceanía	")
Paise.create(:name => "	Moldavia	", :capital => "	Chisinau	", :continente => "	Europa	")
Paise.create(:name => "	Mónaco	", :capital => "	Mónaco	", :continente => "	Europa	")
Paise.create(:name => "	Mongolia	", :capital => "	Ulán Bator	", :continente => "	Asia	")
Paise.create(:name => "	Montenegro	", :capital => "	Podgorica	", :continente => "	Europa	")
Paise.create(:name => "	Mozambique	", :capital => "	Maputo	", :continente => "	África	")
Paise.create(:name => "	Birmania	", :capital => "	Naipyidó	", :continente => "	Asia	")
Paise.create(:name => "	Namibia	", :capital => "	Windhoek	", :continente => "	África	")
Paise.create(:name => "	Nauru	", :capital => "	Yaren	", :continente => "	Oceanía	")
Paise.create(:name => "	Nepal	", :capital => "	Katmandú	", :continente => "	Asia	")
Paise.create(:name => "	Nicaragua	", :capital => "	Managua	", :continente => "	América	")
Paise.create(:name => "	Níger	", :capital => "	Niamey	", :continente => "	África	")
Paise.create(:name => "	Nigeria	", :capital => "	Abuya	", :continente => "	África	")
Paise.create(:name => "	Noruega	", :capital => "	Oslo	", :continente => "	Europa	")
Paise.create(:name => "	Nueva Zelanda	", :capital => "	Wellington	", :continente => "	Oceanía	")
Paise.create(:name => "	Omán	", :capital => "	Mascate	", :continente => "	Asia	")
Paise.create(:name => "	Países Bajos	", :capital => "	Ámsterdam	", :continente => "	Europa	")
Paise.create(:name => "	Pakistán	", :capital => "	Islamabad	", :continente => "	Asia	")
Paise.create(:name => "	Palaos	", :capital => "	Melekeok	", :continente => "	Oceanía	")
Paise.create(:name => "	Panamá	", :capital => "	Panamá	", :continente => "	América	")
Paise.create(:name => "	Papúa Nueva Guinea	", :capital => "	Port Moresby	", :continente => "	Oceanía	")
Paise.create(:name => "	Paraguay	", :capital => "	Asunción	", :continente => "	América	")
Paise.create(:name => "	Perú	", :capital => "	Lima	", :continente => "	América	")
Paise.create(:name => "	Polonia	", :capital => "	Varsovia	", :continente => "	Europa	")
Paise.create(:name => "	Portugal	", :capital => "	Lisboa	", :continente => "	Europa	")
Paise.create(:name => "	Qatar	", :capital => "	Doha	", :continente => "	Asia	")
Paise.create(:name => "	Reino Unido	", :capital => "	Londres	", :continente => "	Europa	")
Paise.create(:name => "	Ruanda	", :capital => "	Kigali	", :continente => "	África	")
Paise.create(:name => "	Rumania	", :capital => "	Bucarest	", :continente => "	Europa	")
Paise.create(:name => "	Rusia	", :capital => "	Moscú	", :continente => "	Europa-Asia	")
Paise.create(:name => "	Islas Salomón	", :capital => "	Honiara	", :continente => "	Oceanía	")
Paise.create(:name => "	Samoa	", :capital => "	Apia	", :continente => "	Oceanía	")
Paise.create(:name => "	San Cristóbal y Nieves	", :capital => "	Basseterre	", :continente => "	América	")
Paise.create(:name => "	San Marino	", :capital => "	Ciudad de San Marino	", :continente => "	Europa	")
Paise.create(:name => "	Santa Lucía	", :capital => "	Castries	", :continente => "	América	")
Paise.create(:name => "	Santo Tomé y Príncipe	", :capital => "	Santo Tomé	", :continente => "	África	")
Paise.create(:name => "	San Vicente y las Granadinas	", :capital => "	Kingstown	", :continente => "	América	")
Paise.create(:name => "	Senegal	", :capital => "	Dakar	", :continente => "	África	")
Paise.create(:name => "	Serbia	", :capital => "	Belgrado	", :continente => "	Europa	")
Paise.create(:name => "	Seychelles	", :capital => "	Victoria	", :continente => "	África	")
Paise.create(:name => "	Sierra Leona	", :capital => "	Freetown	", :continente => "	África	")
Paise.create(:name => "	Singapur	", :capital => "	Singapur	", :continente => "	Asia	")
Paise.create(:name => "	Siria	", :capital => "	Damasco	", :continente => "	Asia	")
Paise.create(:name => "	Somalia	", :capital => "	Mogadiscio	", :continente => "	África	")
Paise.create(:name => "	Sri Lanka	", :capital => "	Sri Jayawardenapura Kotte	", :continente => "	Asia	")
Paise.create(:name => "	Suazilandia	", :capital => "	Mbabane	", :continente => "	África	")
Paise.create(:name => "	Sudáfrica	", :capital => "	Ciudad del Cabo	", :continente => "	África	")
Paise.create(:name => "	Sudán	", :capital => "	Jartum	", :continente => "	África	")
Paise.create(:name => "	Suecia	", :capital => "	Estocolmo	", :continente => "	Europa	")
Paise.create(:name => "	Suiza	", :capital => "	Berna	", :continente => "	Europa	")
Paise.create(:name => "	Surinam	", :capital => "	Paramaribo	", :continente => "	América	")
Paise.create(:name => "	Tailandia	", :capital => "	Bangkok	", :continente => "	Asia	")
Paise.create(:name => "	Tanzania	", :capital => "	Dodoma	", :continente => "	África	")
Paise.create(:name => "	Tayikistán	", :capital => "	Dusambé	", :continente => "	Asia	")
Paise.create(:name => "	Timor Oriental	", :capital => "	Dili	", :continente => "	Asia	")
Paise.create(:name => "	Togo	", :capital => "	Lomé	", :continente => "	África	")
Paise.create(:name => "	Tonga	", :capital => "	Nukualofa	", :continente => "	Oceanía	")
Paise.create(:name => "	Trinidad y Tobago	", :capital => "	Puerto España	", :continente => "	América	")
Paise.create(:name => "	Túnez	", :capital => "	Túnez	", :continente => "	África	")
Paise.create(:name => "	Turkmenistán	", :capital => "	Asjabad	", :continente => "	Asia	")
Paise.create(:name => "	Turquía	", :capital => "	Ankara	", :continente => "	Asia	")
Paise.create(:name => "	Tuvalu	", :capital => "	Funafuti	", :continente => "	Oceanía	")
Paise.create(:name => "	Ucrania	", :capital => "	Kiev	", :continente => "	Europa	")
Paise.create(:name => "	Uruguay	", :capital => "	Montevideo	", :continente => "	América	")
Paise.create(:name => "	Uzbekistán	", :capital => "	Taskent	", :continente => "	Asia	")
Paise.create(:name => "	Vanuatu	", :capital => "	Port Vila	", :continente => "	Oceanía	")
Paise.create(:name => "	Ciudad del Vaticano	", :capital => "	Ciudad del Vaticano	", :continente => "	Europa	")
Paise.create(:name => "	Venezuela	", :capital => "	Caracas	", :continente => "	América	")
Paise.create(:name => "	Vietnam	", :capital => "	Hanói	", :continente => "	Asia	")
Paise.create(:name => "	Yemen	", :capital => "	Saná	", :continente => "	Asia	")
Paise.create(:name => "	Yibuti	", :capital => "	Yibuti	", :continente => "	África	")
Paise.create(:name => "	Zambia	", :capital => "	Lusaka	", :continente => "	África	")
Paise.create(:name => "	Zimbabue	", :capital => "	Harare	", :continente => "	África	")
puts "-----------------------------------------------------------------------------"
puts "Se termino de insertar los paises."
puts "-----------------------------------------------------------------------------"

ActiveRecord::Base.connection.exec_query("Truncate table estados")
puts "-----------------------------------------------------------------------------"
puts "Se realizó un Truncate a la tabla de 'estados' tipo de base de datos 'MySQL'."
puts "-----------------------------------------------------------------------------"

puts "-----------------------------------------------------------------------------"
puts "Comenzando a insertar estados."
puts "-----------------------------------------------------------------------------"
Estado.create(:name => "	Aguascalientes	", :pais => "	México	")
Estado.create(:name => "	Baja California	", :pais => "	México	")
Estado.create(:name => "	Baja California Sur	", :pais => "	México	")
Estado.create(:name => "	Campeche	", :pais => "	México	")
Estado.create(:name => "	Chiapas	", :pais => "	México	")
Estado.create(:name => "	Chihuahua	", :pais => "	México	")
Estado.create(:name => "	Coahuila	", :pais => "	México	")
Estado.create(:name => "	Colima	", :pais => "	México	")
Estado.create(:name => "	Ciudad de México / Distrito Federal	", :pais => "	México	")
Estado.create(:name => "	Durango	", :pais => "	México	")
Estado.create(:name => "	Estado de México	", :pais => "	México	")
Estado.create(:name => "	Guanajuato	", :pais => "	México	")
Estado.create(:name => "	Guerrero	", :pais => "	México	")
Estado.create(:name => "	Hidalgo	", :pais => "	México	")
Estado.create(:name => "	Jalisco	", :pais => "	México	")
Estado.create(:name => "	Michoacán	", :pais => "	México	")
Estado.create(:name => "	Morelos	", :pais => "	México	")
Estado.create(:name => "	Nayarit	", :pais => "	México	")
Estado.create(:name => "	Nuevo León	", :pais => "	México	")
Estado.create(:name => "	Oaxaca	", :pais => "	México	")
Estado.create(:name => "	Puebla	", :pais => "	México	")
Estado.create(:name => "	Querétaro	", :pais => "	México	")
Estado.create(:name => "	Quintana Roo	", :pais => "	México	")
Estado.create(:name => "	San Luis Potosí	", :pais => "	México	")
Estado.create(:name => "	Sinaloa	", :pais => "	México	")
Estado.create(:name => "	Sonora	", :pais => "	México	")
Estado.create(:name => "	Tabasco	", :pais => "	México	")
Estado.create(:name => "	Tamaulipas	", :pais => "	México	")
Estado.create(:name => "	Tlaxcala	", :pais => "	México	")
Estado.create(:name => "	Veracruz	", :pais => "	México	")
Estado.create(:name => "	Yucatán	", :pais => "	México	")
Estado.create(:name => "	Zacatecas	", :pais => "	México	")

Estado.create(:name => "	Alabama (AL)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Alaska (AK)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Arizona (AZ)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Arkansas (AR)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	California (CA)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Carolina del Norte (NC)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Carolina del Sur (SC)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Colorado (CO)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Connecticut (CT)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Dakota del Norte (ND)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Dakota del Sur (SD)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Delaware (DE)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Florida (FL)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Georgia (GA)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Hawái (HI)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Idaho (ID)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Illinois (IL)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Indiana (IN)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Iowa (IA)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Kansas (KS)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Kentucky (KY)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Luisiana (LA)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Maine (ME)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Maryland (MD)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Massachusetts (MA)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Míchigan (MI)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Minnesota (MN)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Misisipi (MS)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Misuri (MO)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Montana (MT)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Nebraska (NE)	", :pais => "	Estados Unidos	")
Estado.create(:name => "	Nevada (NV)	", :pais => "	Estados Unidos	")

puts "-----------------------------------------------------------------------------"
puts "Se termino de insertar los estados."
puts "-----------------------------------------------------------------------------"

